name: ArenaTOW

version: 1.0
author: TcFoxy

description: Awesome Tug of War Plugin!
depend: [BattleArena]  ### <--- the important line
main: io.github.TcFoxy.ArenaTOW.ArenaTOW
commands:
    tow:
        aliases: [TugOfWar]
permissions:
    arenatow.rank.0:
        description: gives you this rank.
        default: false
    arenatow.rank.1: 
        description: gives you this rank.
        default: false
    arenatow.rank.2: 
        description: gives you this rank.
        default: false
    arenatow.rank.3: 
        description: gives you this rank.
        default: false
    arenatow.rank.4: 
        description: gives you this rank.
        default: false
    arenatow.rank.5: 
        description: gives you this rank.
        default: false
    arenatow.rank.6: 
        description: gives you this rank.
        default: false
    arenatow.rank.7: 
        description: gives you this rank.
        default: false
    arenatow.rank.8: 
        description: gives you this rank.
        default: false
    arenatow.rank.9: 
        description: gives you this rank.
        default: false
    arenatow.rank.10: 
        description: gives you this rank.
        default: false
    arenatow.rank.11: 
        description: gives you this rank.
        default: false
    arenatow.rank.12: 
        description: gives you this rank.
        default: false
    arenatow.rank.13: 
        description: gives you this rank.
        default: false
    arenatow.rank.14: 
        description: gives you this rank.
        default: false
    arenatow.rank.15: 
        description: gives you this rank.
        default: false
    arenatow.rank.16: 
        description: gives you this rank.
        default: false
    arenatow.rank.17: 
        description: gives you this rank.
        default: false
    arenatow.rank.18: 
        description: gives you this rank.
        default: false
    arenatow.rank.19: 
        description: gives you this rank.
        default: false
