#I strongly recommend only changing things if you have a backup of this,
#It's very easy to break the game with this file. 
ArenaTow:
  name: ArenaTow
  command: tow
  prefix: '&8[Tug Of War]'
  signDisplayName: 8[TugofWar]
  gameSize:
    nTeams: '2'
    teamSize: '3'
  nLives: 'infinite'
  victoryCondition: Custom
  arenaType: ArenaTow #dont change
  arenaClass: TugArena #dont change
  
#95% sure these are in order of occurance  
  preReqs: 
    options:
    - clearInventory
  onJoin: #When the player types /tow join
    options:
    - pvpOff
    - teleportWaitroom
  onEnter:
    options:
    - STOREALL
  onPreStart: #The couple seconds before the game is live
    options:
    - woolTeams
    - pvpOff
  onStart: #When the game becomes live
    options:
    - teleportIn
    - pvpOn
  onComplete: #When someone wins
    options:
    - teleportOut
    - clearInventory
  winners:
#    enchants:
#    - speed:1:900
#    - prot:1:900
#    options:
#    - health=20.0
#    - hunger=20
#    - experience=300
#    - money=1.0
  onLeave:
    options:
    - RESTOREALL